version: "3.9"

services:
  probusinesscard:
    build: .
    image: probusinesscard:latest
    container_name: probusinesscard
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true